FROM python:3.11-slim


WORKDIR /app


COPY requirements.txt ./
RUN pip install -r requirements.txt


COPY . .

EXPOSE 8000

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["bash", "-c", "/wait-for-it.sh db:5432 -- \
    alembic history | grep 'Initial migration' && \
    echo 'Migration already exists, applying migrations only...' && \
    alembic upgrade head || \
    (echo 'Creating initial migration and applying it...' && \
    alembic revision --autogenerate -m 'Initial migration' && \
    alembic upgrade head) && \
    python3 db/seed.py  && \
    uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
