from .controllers.address import address_router
from .controllers.auth import auth_router
from .controllers.cart import cart_router
from .controllers.cart_items import cart_items_routes
from .controllers.category import category_router
from .controllers.client_routes import client_router
from .controllers.invoice_items import invoice_items_router
from .controllers.invoices import invoices_router
from .controllers.KPIs import KPIsRouter
from .controllers.paypal import paypal_router
from .controllers.products import products_router
from .controllers.report import report_router
from .controllers.roles import roles_router
from .controllers.stocks import stocks_router
from .controllers.users import users_router
from .controllers.wishlist import wishlist_router
