name: 🧾 Commit Message Lint

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: ✅ Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧾 Run Commitlint
        uses: wagoid/commitlint-github-action@v6
